
services:
  sacbm:
    build:
      args:
        - COMPOSE_PROJ_NAME=${COMPOSE_PROJ_NAME}
      context: ..
      dockerfile: ./.docker/Dockerfile
    environment:
      - TMUX=$TMUX
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/workspaces/${COMPOSE_PROJ_NAME}
      - /storage-01/datasets:/workspaces/${COMPOSE_PROJ_NAME}/datasets
    shm_size: '50g'
